"use client";
import { useEffect, useMemo, useState } from "react";
const logoFor=a=>a.logoKey==="rcso"?"/county-governance/rcso-logo.png":a.logoKey==="rdot"?"/county-governance/rdot-logo.png":null;
export default function CountyGovernance(){
 const [data,setData]=useState(null),[view,setView]=useState(null),[selected,setSelected]=useState(null),[query,setQuery]=useState("");
 useEffect(()=>{fetch("/api/county-governance",{cache:"no-store"}).then(r=>r.json()).then(p=>setData(p.state||null))},[]);
 const agencies=useMemo(()=>{const q=query.trim().toLowerCase();return (data?.agencies||[]).filter(a=>!q||`${a.name} ${a.abbreviation} ${a.category}`.toLowerCase().includes(q))},[data,query]);
 if(!data)return <div className="gov-loading"><span/></div>;
 if(!view)return <div className="gov-landing"><button onClick={()=>setView("government")}><b>🏛</b><strong>County Administration</strong><span>Governor, Cabinet, Senate und aktuelle Regierungsmehrheit</span></button><button onClick={()=>setView("agencies")}><b>▦</b><strong>County Agencies</strong><span>Offizielles Verzeichnis der Behörden und öffentlichen Einrichtungen</span></button></div>;
 if(view==="agencies")return <div className="gov-shell"><header><button onClick={()=>{setView(null);setSelected(null)}}>← Übersicht</button><div><h2>County Agencies</h2><p>Offizielles Behördenverzeichnis von Riverside County</p></div></header><div className="gov-agency-layout"><aside><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Behörde suchen …"/>{agencies.map(a=><button key={a.id} className={selected?.id===a.id?"active":""} onClick={()=>setSelected(a)}><i>{logoFor(a)?<img src={logoFor(a)} alt=""/>:a.abbreviation}</i><span><strong>{a.name}</strong><small>{a.category}</small></span></button>)}</aside><section>{!selected?<div className="gov-empty">Behörde auswählen.</div>:<article className="gov-agency-profile"><div className="gov-agency-heading">{logoFor(selected)?<img src={logoFor(selected)} alt=""/>:<div className="gov-logo-placeholder">{selected.abbreviation}</div>}<div><span>{selected.category}</span><h2>{selected.name}</h2><p>{selected.abbreviation} · {selected.status}</p></div></div><p className="gov-description">{selected.description}</p><dl><dt>Behördenleitung</dt><dd>{selected.administrator||"Nicht eingetragen"}</dd><dt>Kontakt</dt><dd>County Extension {selected.extension||"—"}</dd><dt>Rechtsgrundlage</dt><dd>{selected.legalAuthority||"—"}</dd><dt>Status</dt><dd>{selected.status||"—"}</dd><dt>Website / Terminal</dt><dd>{selected.websiteUrl?<a href={selected.websiteUrl} target="_blank" rel="noreferrer">Website öffnen</a>:<span className="gov-disabled-link">Derzeit nicht hinterlegt</span>}</dd></dl></article>}</section></div><GovFooter data={data}/></div>;
 const g=data.government;const counts=g.senate.reduce((m,s)=>(m[s.party]=(m[s.party]||0)+1,m),{});
 return <div className="gov-shell"><header><button onClick={()=>setView(null)}>← Übersicht</button><div><h2>County Administration</h2><p>Aktuelle Regierung von Riverside County</p></div></header><section className="gov-government"><article className="gov-governor"><img src={g.governor.portraitPath}/><div><span>GOVERNOR OF RIVERSIDE COUNTY</span><h1>{g.governor.name}</h1><strong>{g.governor.party}</strong><p>{g.governor.biography}</p><small>Amtszeit: {g.governor.term}</small></div><img className="gov-party-logo" src={g.rulingParty.logoPath}/></article><div className="gov-government-grid"><article><h3>Gubernatorial Election {g.election.year}</h3>{g.election.results.map(r=><div className="gov-result" key={r.short}><span>{r.party}</span><b>{r.percent}%</b><i><em style={{width:`${r.percent}%`}}/></i></div>)}</article><article><h3>Ruling Party</h3><div className="gov-party-card"><img src={g.rulingParty.logoPath}/><div><strong>{g.rulingParty.name}</strong><p>{g.rulingParty.description}</p></div></div><h4>Senate Composition</h4>{Object.entries(counts).map(([p,c])=><p className="gov-composition" key={p}><span>{p}</span><b>{c} / 20</b></p>)}</article></div><article className="gov-section"><h3>State Cabinet</h3><div className="gov-cabinet">{g.cabinet.map(x=><div key={x.office}><span>{x.office}</span><strong>{x.name}</strong></div>)}</div></article><article className="gov-section"><h3>Riverside Senate</h3><div className="gov-senate">{g.senate.map(x=><div key={x.district}><span>{x.district}</span><strong>{x.name}</strong><small>{x.party} · {x.committee}</small></div>)}</div></article></section><GovFooter data={data}/></div>;
}
function GovFooter({data}){return <footer className="gov-footer"><strong>Official County Record</strong><span>Last Updated: {new Date(data.lastUpdated).toLocaleDateString("de-DE")}</span><span>Maintained by: {data.maintainedBy}</span></footer>}
